version: 2

jobs:
  build:
    working_directory: ~/src/proxy
    docker:
      - image: gcr.io/istio-testing/istio-builder:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}
      - restore_cache:
          keys:
            - repo-cache-{{ checksum "WORKSPACE" }}
      - run: make build
      - run: make test
      - save_cache:
          key: repo-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.repo      
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/src/proxy/.cache/bazel
      - store_artifacts:
          path: /home/circleci/logs


workflows:
  version: 2
  all:
    jobs:
      - build
