version: 2

jobs:
  build:
    #working_directory: src/proxy
    environment:
    docker:
      - image: costinm/proxy-builder:0.4.4
      #- image: gcr.io/istio-testing/istio-builder:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}
      - restore_cache:
          keys:
            - repo-cache-{{ checksum "WORKSPACE" }}
      # To build docker containers or run tests in a docker
      - setup_remote_docker
      - run: make build_envoy
      - run: make test_envoy
      - save_cache:
          key: repo-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.repo      
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/src/proxy/.cache/bazel
      - store_artifacts:
          path: /home/circleci/logs




workflows:
  version: 2
  all:
    jobs:
      - build
