version: 2

jobs:
  build:
    working_directory: /workspace/istio/src/proxy
    environment:
      - USER: istio-builder
      - UID: 1000
      - GID: 1000
      - HOME: /workspace
      - ROOT_SETUP: /bin/true
    docker:
      #- image: gcr.io/istio-testing/istio-builder:0.4.5-bazel7-go19
      - image: gcr.io/istio-testing/istio-builder:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}
      - restore_cache:
          keys:
            - repo-cache-{{ checksum "WORKSPACE" }}
      # To build docker containers or run tests in a docker
      - setup_remote_docker
      - run: (cd /workspace/istio/src/proxy; make build_envoy)
      - run: (cd /workspace/istio/src/proxy; make test_envoy)
      - save_cache:
          key: repo-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.repo      
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/src/proxy/.cache/bazel
      - store_artifacts:
          path: /home/circleci/logs


workflows:
  version: 2
  all:
    jobs:
      - build
