steps:

- name: 'costinm/proxy-builder:0.4.4'
  args: ['make', 'artifacts_cached', "ISTIO_TAGS=git_latest"]
- name: gcr.io/cloud-builders/gsutil
  args: ['cp','/builder/home/bazel_cache.tgz', 'gs://$PROJECT_ID/proxy_cache']

# Build other artifacts ( deb files )
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'bazel-bin/tools/deb/istio-proxy.deb', 'gs://istio/istio-proxy-master.deb']

images:
-  'gcr.io/$PROJECT_ID/proxy_debug'

timeout: 1800s
